bepensa-ss-crm/Areas/Home/Controllers/IniciosController.cs
using bepensa_biz.Interfaces;
using bepensa_data.models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace bepensa_ss_crm.Areas.Home.Controllers
{
    [Area("Home")]
    [Authorize]
    public class IniciosController : Controller
    {
        private readonly IAccessSession _sesion;
        private readonly IDireccion _colonia;

        public IniciosController(IAccessSession sesion, IDireccion colonia)
        {
            _sesion = sesion;
            _colonia = colonia;
        }

        [HttpGet("home")]
        public IActionResult Index()
        {
            return View();
        }

        #region Dirección
        /// <summary>
        /// Consulta las colonias con base al código postal
        /// </summary>
        /// <param name="CP"></param>
        /// <returns>Lista de colonias</returns>
        [HttpGet("consulta/colonias/{CP}")]
        public async Task<JsonResult> ConsultarColonia(string CP)
        {
            var resultado = await _colonia.ConsultarColonias(CP);

            return Json(resultado);
        }

        [HttpGet("consulta/municipio/{idColonia}")]
        public async Task<JsonResult> ConsultarMunicipio(int idColonia)
        {
            var resultado = await _colonia.ConsultarMunicipio(idColonia);

            return Json(resultado);
        }

        [HttpGet("consulta/estado/{idMunicipio}")]
        public async Task<JsonResult> ConsultarEstado(int idMunicipio)
        {
            var resultado = await _colonia.ConsultarEstado(idMunicipio);

            return Json(resultado);
        }
        #endregion
    }
}

bepensa-ss-crm/Areas/Usuario/Controllers/LlamadasController.cs
using bepensa_biz.Interfaces;
using bepensa_models.DataModels;
using bepensa_ss_crm.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace bepensa_ss_crm.Areas.Usuario.Controllers
{
    [Area("Usuario")]
    [Authorize]
    [ValidaSesionUsuario]
    public class LlamadasController : Controller
    {
        private IAccessSession _sesion { get; set; }

        private readonly IDropDownList _listas;
        private readonly ILlamada _llamada;

        public LlamadasController(IAccessSession sesion, ILlamada llamada, IDropDownList listas)
        {
            _sesion = sesion;
            _llamada = llamada;
            _listas = listas;
        }

        [HttpGet("llamadas")]
        public IActionResult Index()
        {
            return View(new LlamadaRequest());
        }

        [HttpGet("llamadas/historico")]
        public IActionResult Historico()
        {
            var resultado = _llamada.ConsultarLlamadas(_sesion.UsuarioActual.Id);

            return View(resultado.Data);
        }

        public IActionResult CapturaRapida()
        {
            return PartialView("_llamadaModal");
        }

        [HttpGet("llamadas/{id}/subcategorias-llamada")]
        public JsonResult Subcategoria(int id)
        {
            var resultado = _listas.SubcategoriasLlamada(id);

            return Json(resultado);
        }

        [HttpPost("llamadas/registrar-llamada")]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> RegistrarLlamada(LlamadaRequest pLlamada)
        {
            pLlamada.IdOperador = _sesion.OperadorActual.Id;

            var resultado = await _llamada.RegistrarLlamada(pLlamada);

            return Json(resultado);
        }

        [HttpGet("llamadas/{id}/seguimiento-llamada")]
        public JsonResult SeguimientoLlamada(int id)
        {
            var resultado = _listas.SuperLlamadas(id);

            return Json(resultado);
        }
    }
}

bepensa-ss-crm/Areas/Usuario/Controllers/SociosController.cs
using bepensa_biz.Interfaces;
using bepensa_data.models;
using bepensa_models.CRM;
using bepensa_models.DataModels;
using bepensa_models.DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace bepensa_ss_crm.Areas.Usuario.Controllers
{
    [Area("Usuario")]
    [Authorize]
    public class SociosController : Controller
    {
        private IAccessSession _sesion { get; set; }
        private readonly IDireccion _colonia;
        private readonly IUsuario _usuario;

        public SociosController(IUsuario usuario, IAccessSession sesion, IDireccion colonia)
        {
            _usuario = usuario;
            _sesion = sesion;
            _colonia = colonia;
        }

        [HttpGet("socios")]
        public IActionResult Index()
        {
            _sesion.UsuarioActual = null;

            return View();
        }

        [HttpPost("socios/buscar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Buscar(BuscarRequest pBuscar)
        {
            List<UsuarioDTO> model = [];

            var resultado = await _usuario.BuscarUsuario(pBuscar);

            if (resultado.Data != null && resultado.Data.Count > 0)
            {
                model = resultado.Data;
            }

            return PartialView("_sociosTable", model);
        }

        [HttpGet("socios/detalle/{idUsuario}")]
        public async Task<IActionResult> Socio(int idUsuario, string? msg)
        {
            if (_sesion.UsuarioActual == null || _sesion.UsuarioActual.Id != idUsuario || _sesion.ForzarCambio)
            {
                var resultado = await _usuario.BuscarUsuario(idUsuario);

                _sesion.UsuarioActual = resultado.Data;

                _sesion.ForzarCambio = false;
            }
            if (msg != null)
                TempData["SuccessMensaje"] = msg;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ActualizarSocio(UsuarioRequest usuarioRequest)
        {

            var resultado = await _usuario.Actualizar(usuarioRequest, _sesion.OperadorActual.Id);

            _sesion.UsuarioActual = resultado.Data;

            //ViewBag.SuccessMensaje = resultado.Mensaje;

            return RedirectToAction("Socio", new { idUsuario = usuarioRequest.Id, msg = resultado.Mensaje });


            //return PartialView("_sociosTable", model);
        }
    }
}

bepensa-ss-crm/Areas/Usuario/Views/Llamadas/Historico.cshtml
@model List<LlamadaDTO>

@{
    ViewData["Title"] = "Historico de llamadas";
}

<div class="page-body">
    <div class="container-fluid">
        <div class="page-title">
            <div class="row">
                <div class="col-6">
                    <h3>Buscar socio</h3>
                </div>
                <div class="col-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a asp-action="Index" asp-controller="Inicios" asp-area="Home">
                                <svg class="stroke-icon">
                                    <use href="/assets/svg/icon-sprite.svg#stroke-home"></use>
                                </svg>
                            </a>
                        </li>
                        <li class="breadcrumb-item">Socios</li>
                        <li class="breadcrumb-item active">Buscar</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 project-list">
                <div class="card">
                    <div class="card-header">
                        <partial name="_menuPrincipal" />
                        <div class="row">
                            <div class="col-12">
                                <a class="btn btn-outline-primary" asp-action="Index" asp-controller="Llamadas" asp-area="Usuario">Captura de Llamada</a>
                                <a class="btn btn-primary" asp-action="Historico" asp-controller="Llamadas" asp-area="Usuario">Hístorico de Llamadas</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">

                        <div class="col-12">
                            <div class="table-responsive">
                                <table class="table table-striped table-hover">
                                    <thead>
                                        <tr>
                                            <th>Folio</th>
                                            <th>Fecha Captura</th>
                                            <th>Descripción</th>
                                            <th>Usuario Captura</th>
                                            <th>Fecha Último Comentario</th>
                                            <th>Último comentario</th>
                                            <th>Usuario Último comentario</th>
                                            <th>Tipo de Llamada</th>
                                            <th>Motivo</th>
                                            <th>Estatus</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model != null && Model.Count > 0)
                                        {
                                            foreach (var modelo in Model)
                                            {
                                                <tr role="row" class="odd">
                                                    <td>@modelo.Id</td>
                                                    <td>@modelo.FechaReg.ToString("dd/MM/yyyy")</td>
                                                    <td>@modelo.Tema</td>
                                                    <td>@modelo.OperadorReg.Nombre</td>
                                                    <td>
                                                        @if (modelo.Llamadas != null && modelo.Llamadas.Count > 0)
                                                        {
                                                            @modelo.Llamadas.OrderByDescending(x => x.Id).Select(x => x.FechaReg).FirstOrDefault().ToString("dd/MM/yyyy")
                                                        }
                                                        else
                                                        {
                                                            @modelo.FechaReg.ToString("dd/MM/yyyy")
                                                        }
                                                    </td>
                                                    <td>
                                                        @if (modelo.Llamadas != null && modelo.Llamadas.Count > 0)
                                                        {
                                                            @modelo.Llamadas.OrderByDescending(x => x.Id).Select(x => x.Comentario).FirstOrDefault()
                                                        }
                                                        else
                                                        {
                                                            @modelo.Comentario
                                                        }
                                                    </td>
                                                    <td>
                                                        @if (modelo.Llamadas != null && modelo.Llamadas.Count > 0)
                                                        {
                                                            @modelo.Llamadas.OrderByDescending(x => x.Id).Select(x => x.OperadorReg.Nombre).FirstOrDefault()
                                                        }
                                                        else
                                                        {
                                                            @modelo.OperadorReg.Nombre
                                                        }
                                                    </td>
                                                    <td>
                                                        @modelo.TipoLlamada
                                                    </td>
                                                    <td>
                                                       @modelo.CategoriaLlamada
                                                    </td>
                                                    <td>
                                                        @modelo.EstatusLlamada
                                                    </td>
                                                </tr>
                                            }
                                        }
                                        else
                                        {
                                            <tr role="1">
                                                <td colspan="13" class="text-center">No hay datos para mostrar</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid Ends-->
</div>

bepensa-ss-crm/Areas/Usuario/Views/Llamadas/Index.cshtml
@model LlamadaRequest
@inject IDropDownList Listas;

@{
    ViewData["Title"] = "Llamada";
}
<div class="page-body">
    <div class="container-fluid">
        <div class="page-title">
            <div class="row">
                <div class="col-6">
                    <h3>Socio</h3>
                </div>
                <div class="col-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a asp-action="Index" asp-controller="Inicios" asp-area="Home">
                                <svg class="stroke-icon">
                                    <use href="/assets/svg/icon-sprite.svg#stroke-home"></use>
                                </svg>
                            </a>
                        </li>
                        <li class="breadcrumb-item">
                            <a asp-action="Index" asp-controller="Socios" asp-area="Usuario">Buscar</a>
                        </li>
                        <li class="breadcrumb-item active"> Cliente</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <!-- Container-fluid starts-->
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 project-list">
                <div class="card">
                    <div class="card-header">
                        <partial name="_menuPrincipal" />
                        <div class="row">
                            <div class="col-12">
                                <a class="btn btn-outline-primary" asp-action="Historico" asp-controller="Llamadas" asp-area="Usuario">Hístorico de Llamadas</a>
                                <a class="btn btn-primary" asp-action="Index" asp-controller="Llamadas" asp-area="Usuario">Captura de Llamada</a>
                            </div>
                        </div>
                    </div>
                    <div class="row card-body">
                        <div class="col-12">
                            <form class="form theme-form" id="formRegLlamada" asp-area="Usuario" asp-controller="Llamadas" asp-action="RegistrarLlamada" asp-antiforgery="true" method="post">
                                <div class="row mb-3">
                                    <div class="col col-md-4">
                                        <label class="form-label" asp-for="IdTipoLlamada"></label>
                                        <select class="form-control" asp-for="IdTipoLlamada" asp-items="Listas.TiposLlamada()">
                                            <option value="" selected>Seleccione una opción</option>
                                        </select>
                                        <span asp-validation-for="IdTipoLlamada" class="text-danger warninglogin"></span>
                                    </div>
                                    <div class="col col-md-8">
                                        <input type="hidden" id="txtIdUsuario" asp-for="IdUsuario" value="@Sesion.UsuarioActual.Id" />
                                        <label class="form-label" asp-for="Nombre"></label>
                                        <input type="text" class="form-control" asp-for="Nombre" />
                                        <span asp-validation-for="Nombre" class="text-danger warninglogin"></span>
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <div class="col col-md-12">
                                        <label class="form-label" asp-for="IdPadre"></label>
                                        <select id="ddlSeguimientoLlamada" class="form-control" asp-for="IdPadre" asp-items="Listas.SuperLlamadas(Sesion.UsuarioActual.Id)">
                                            <option value="" selected>Seleccione una opción</option>
                                        </select>
                                        <span asp-validation-for="IdPadre" class="text-danger warninglogin"></span>
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <div class="col col-md-8">
                                        <label class="form-label" asp-for="Tema">Motivo*</label>
                                        <input type="text" class="form-control" asp-for="Tema" />
                                        <span asp-validation-for="Tema" class="text-danger warninglogin"></span>
                                    </div>
                                    <div class="col">
                                        <label class="form-label" asp-for="Telefono"></label>
                                        <input type="tel" class="form-control" asp-for="Telefono" />
                                        <span asp-validation-for="Telefono" class="text-danger warninglogin"></span>
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <div class="col col-md-6">
                                        <label class="form-label">Categoría de llamada*</label>
                                        <select id="ddlCategoriaLlamada" class="form-control" asp-items="Listas.CategoriasLlamada()">
                                            <option value="" selected>Seleccione una opción</option>
                                        </select>
                                        @* <span asp-validation-for="IdTdl" class="text-danger warninglogin"></span> *@
                                    </div>

                                    <div class="col col-md-6">
                                        <label class="form-label" asp-for="IdSubcategoriaLlamada"></label>
                                        <select id="ddlIdSubcategoriaLlamada" asp-for="IdSubcategoriaLlamada" class="form-control">
                                            <option value="" selected>Seleccione una opción</option>
                                        </select>
                                        <span asp-validation-for="IdSubcategoriaLlamada" class="text-danger warninglogin"></span>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col">
                                        <label class="form-label" asp-for="Comentario"></label>
                                        <textarea class="form-control" asp-for="Comentario" rows="3"></textarea>
                                        <span asp-validation-for="Comentario" class="text-danger warninglogin"></span>
                                    </div>
                                </div>

                                <div class="row justify-content-end">
                                    <div class="col-4 col-md-5">
                                        <label class="form-label" asp-for="IdEstatusLlamada"></label>
                                        <select class="form-control" asp-for="IdEstatusLlamada" asp-items="Listas.EstatusLlamada()">
                                            <option value="" selected>Seleccione una opción</option>
                                        </select>
                                        <span asp-validation-for="IdEstatusLlamada" class="text-danger warninglogin"></span>
                                    </div>
                                </div>
                                <hr />
                                <div class="d-flex justify-content-end w-100 g-3">
                                    <div class="col-auto">
                                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button>
                                    </div>
                                    <div class="col-auto mx-2">
                                        <button class="btn btn-primary">Guardar</button>
                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid Ends-->
</div>
@section Scripts {
    <script nonce="@ViewBag.Nonce" type="text/javascript">
        $(document).ready(function () {
            $(document).on('change', '#ddlCategoriaLlamada', function () {

                let id = $(this).val();

                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("Subcategoria", "Llamadas", new { area = "Usuario", id = "__ID__" })'.replace('__ID__', id),
                    success: function (result) {
                        $('#ddlIdSubcategoriaLlamada').empty();

                        $('#ddlIdSubcategoriaLlamada').append('<option value="" selected>Seleccione una opción</option>');

                        if (result && result.length > 0) {
                            result.forEach(function (subcategoria) {
                                $('#ddlIdSubcategoriaLlamada').append(
                                    `<option value="${subcategoria.value}">${subcategoria.text}</option>`
                                );
                            });
                        } else {
                            mostrarMensaje("error", 'No hay subcategorías', "¡Error!");
                        }
                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            });
        });
    </script>
    <script nonce="@ViewBag.Nonce" type="text/javascript">
        $(document).ready(function () {
            var mensajeError = '@Html.Raw(TempData["ErrorMensaje"] ?? "")';
            var mensajeAlert = '@Html.Raw(TempData["AlertMensaje"] ?? "")';
            var mensajeExito = '@Html.Raw(TempData["SuccessMensaje"] ?? "")';

            if (mensajeExito) {
                mostrarMensaje("success", mensajeExito, "Ok!");
            }

            if (mensajeError) {
                mostrarMensaje("error", mensajeError, "¡Error!");
            }

            if (mensajeAlert) {
                mostrarMensaje("warning", mensajeAlert, "¡Error!");
            }

            $(document).on('submit', '#formRegLlamada', function (e) {
                e.preventDefault();

                AbrirLoad();

                var formData = $(this).serialize();

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("RegistrarLlamada", "Llamadas", new { area = "Usuario" })',
                    data: formData,
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    dataType: 'json',
                    success: function (result) {

                        if (result.exitoso) {
                            $('#formRegLlamada')[0].reset();

                            $('#llamadaModal').modal('hide');

                            ActualizarSegLlamada();

                            CerrarLoad();

                            mostrarMensaje("success", mensajeExito, "Registro exitoso!");

                        } else {
                            mostrarMensaje("error", mensajeError, result.mensaje);
                        }
                    },
                    error: function (error) {
                        CerrarLoad();

                        mostrarMensaje("error", mensajeError, "¡Error!");
                    }
                });
            });

            function ActualizarSegLlamada() {
                let id = $('#txtIdUsuario').val();

                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("SeguimientoLlamada", "Llamadas", new { area = "Usuario", id = "__ID__" })'.replace('__ID__', id),
                    success: function (result) {
                        $('#ddlSeguimientoLlamada').empty();

                        $('#ddlSeguimientoLlamada').append('<option value="" selected>Seleccione una opción</option>');

                        if (result && result.length > 0) {
                            result.forEach(function (data) {
                                $('#ddlSeguimientoLlamada').append(
                                    `<option value="${data.value}">${data.text}</option>`
                                );
                            });
                        }
                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            }
        });
    </script>
}